blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Help
    url: https://github.com/BryanJames16/RelaySpark/discussions
    about: Please ask questions or request support in GitHub Discussions.
