##
# @file         default-test.mk
# @brief        Default variable for test jobs.
# @author       Bryan James
# @date         2025-06-12
#
# This mk file contains variable definition for test jobs.
##

## angular-lint
ANGULAR_LINT_APP_PATH = ./
ANGULAR_LINT_ADDITIONAL_PARAMETERS :=

## angular-test
ANGULAR_TEST_APP_PATH = ./
ANGULAR_TEST_ENABLE_FILE_WATCHING = false
ANGULAR_TEST_ADDITIONAL_PARAMETERS :=

## axe-scan
AXE_SCAN_RESULTS_CSV = ./results.csv
AXE_SCAN_ADDITIONAL_PARAMTERS :=
AXE_SCAN_SUMMARY_ENABLED = false
AXE_SCAN_SUMMARY_ADDITIONAL_PARAMTERS :=

## cargo-test
CARGO_TEST_APP_PATH = ./Cargo.toml
CARGO_TEST_ADDITIONAL_PARAMETERS :=

## cargo-validate
CARGO_VALIDATE_APP_PATH = ./Cargo.toml
CARGO_VALIDATE_FMT_ADDITIONAL_PARAMETERS :=
CARGO_VALIDATE_CHECK_ADDITIONAL_PARAMETERS :=
CARGO_VALIDATE_CLIPPY_ADDITIONAL_PARAMETERS :=

## dotnet-test
DOTNET_TEST_TOOL = xunit
DOTNET_TEST_SP_PATH = ./
DOTNET_TEST_VERBOSITY = --normal
DOTNET_TEST_ADDITIONAL_PARAMETERS :=

## go-test
GO_TEST_APPLICATION_PATH = ./
GO_TEST_COVER_PROFILE = coverage.out
GO_TEST_TOOL_COVER_OUTPUT = -html=coverage.out
GO_TEST_ADDITIONAL_PARAMETERS :=
GO_TEST_TOOL_COVER_ADDITIONAL_PARAMETERS :=

## helm-lint
HELM_CHART_PACKAGE_LINT_PATH = ./
HELM_CHART_PACKAGE_LINT_NAME = helm_app
HELM_CHART_PACKAGE_LINT_ADDITIONAL_PARAMETERS :=

## helm-template
HELM_CHART_PACKAGE_TEMPLATE_PATH = ./
HELM_CHART_PACKAGE_TEMPLATE_NAME = helm_app
HELM_CHART_PACKAGE_TEMPLATE_ADDITIONAL_PARAMETERS :=

## helm-test
HELM_CHART_TEST_PATH = ./
HELM_CHART_TEST_NAME = helm_app
HELM_CHART_TEST_NAMESPACE = default
HELM_CHART_TEST_ADDITIONAL_PARAMETERS :=

## maven-test
MAVEN_TEST_PROJECT_PATH = ./
MAVEN_TEST_VERBOSITY = --errors
MAVEN_TEST_ADDITIONAL_PARAMETERS :=

## maven-validate
MAVEN_VALIDATE_PROJECT_PATH = ./
MAVEN_VALIDATE_VERBOSITY = --errors
MAVEN_VALIDATE_ADDITIONAL_PARAMETERS :=

## npm-test
NPM_TEST_ADDITIONAL_PARAMETERS :=

## pa11y
PA11Y_CI_CONFIG = ./
PA11Y_CI_SITEMAP = https://127.0.0.1/sitemap
PA11Y_CI_ADDITIONAL_PARAMETERS :=

## terraform-validate
TERRAFORM_VALIDATE_ADDITIONAL_PARAMETERS :=

## tofu-validate
TOFU_VALIDATE_ADDITIONAL_PARAMETERS :=

## yaml-schema-lint
YAML_SCHEMA_LINT_SCHEMA_PATH = ./schema.yaml
YAML_SCHEMA_LINT_SCAN_PATH = ./values.yaml
YAML_SCHEMA_LINT_ADDITIONAL_PARAMETERS :=
