##
# @file         default-build.mk
# @brief        Default variable for build jobs.
# @author       Bryan James
# @date         2025-06-12
#
# This mk file contains variable definition for build jobs.
##

## cargo-build
CARGO_BUILD_MANIFEST_PATH = ./Cargo.toml
CARGO_BUILD_ADDITIONAL_PARAMETERS :=

## docker-build
CONTAINER_BUILD_IMAGE_NAME = app_image
CONTAINER_BUILD_IMAGE_TAG = v1.0.0
DOCKERFILE_PATH = ./
CONTAINER_BUILD_ADDITIONAL_PARAMETERS :=

## dotnet-build
DOTNET_BUILD_SP_PATH = ./
DOTNET_BUILD_VERBOSITY = minimal
DOTNET_BUILD_ADDITIONAL_PARAMETERS :=

## go-build
GO_BUILD_APPLICATION_PATH = ./
GO_BUILD_OUTPUT_PATH = ./publish
GO_BUILD_ADDITIONAL_PARAMETERS :=

## helm-build
HELM_CHART_BUILD_PATH = ./
HELM_CHART_BUILD_NAME = helm_app
HELM_CHART_BUILD_VERSION = v1.0.0
HELM_CHART_BUILD_ADDITIONAL_PARAMETERS :=

## kaniko-build
KANIKO_BUILD_IMAGE_NAME = app_image
KANIKO_BUILD_IMAGE_TAG = v1.0.0
KANIKO_DOCKER_AUTH_CONFIG_ENABLED = false
KANIKO_DOCKER_AUTH_CONFIG :=
KANIKO_DOCKERFILE_PATH = ./Dockerfile
KANIKO_BUILD_PROJECT_DIR = ./
KANIKO_BUILD_ADDITIONAL_PARAMETERS :=

## maven-build
MAVEN_BUILD_PROJECT_PATH = ./
MAVEN_BUILD_VERBOSITY = --errors
MAVEN_BUILD_ADDITIONAL_PARAMETERS :=

## npm-build
NPM_BUILD_DIRECTORY = ./
NPM_BUILD_INSTALL_ADDITIONAL_PARAMETERS :=
NPM_BUILD_ADDITIONAL_PARAMETERS :=

## npm-clean-build
NPM_CLEAN_BUILD_DIRECTORY = ./
NPM_CLEAN_BUILD_INSTALL_ADDITIONAL_PARAMETERS :=
NPM_CLEAN_BUILD_ADDITIONAL_PARAMETERS :=

## terraform-plan
TERRAFORM_PLAN_PLAN_FILE_NAME = planfile
TERRAFORM_PLAN_ADDITIONAL_PARAMETERS :=

## terraform-apply
TERRAFORM_APPLY_PLAN_FILE_NAME = planfile
TERRAFORM_APPLY_ADDITIONAL_PARAMETERS :=

## tofu-apply
TOFU_APPLY_PLAN_FILE_NAME = planfile
TOFU_APPLY_ADDITIONAL_PARAMETERS :=

## tofu-plan
TOFU_PLAN_PLAN_FILE_NAME = planfile
TOFU_PLAN_ADDITIONAL_PARAMETERS :=
